import type { NextApiRequest, NextApiResponse, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import validateSession from "../../helpers/validateSession";
import useRegister from "../../hooks/register.hook";

const Register: NextPage = () => {
  const { setEmail, setPassword, sendRegisterData, setName } = useRegister();
  return (
    <div>
      <Head>
        <title>Hitman APP - LOGIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="row">
          <div className="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div className="card border-0 shadow rounded-3 my-5">
              <div className="card-body p-4 p-sm-5">
                <h5 className="card-title text-center mb-5 fw-light fs-5">
                  Sign In
                </h5>
                <form>
                  <div className="form-floating mb-3">
                    <input
                      type="email"
                      className="form-control"
                      id="floatingInput"
                      placeholder="name@example.com"
                      onChange={({ target }) => setEmail(target.value)}
                    />
                    <label htmlFor="floatingInput">Email address</label>
                  </div>
                  <div className="form-floating mb-3">
                    <input
                      type="string"
                      className="form-control"
                      id="floatingInput"
                      placeholder="name@example.com"
                      onChange={({ target }) => setName(target.value)}
                    />
                    <label htmlFor="floatingInput">Hitman name</label>
                  </div>
                  <div className="form-floating mb-3">
                    <input
                      type="password"
                      className="form-control"
                      id="floatingPassword"
                      placeholder="Password"
                      onChange={({ target }) => setPassword(target.value)}
                    />
                    <label htmlFor="floatingPassword">Password</label>
                  </div>

                  <div className="form-check mb-3">
                    <Link className="form-check-label" href="/">
                      Sign In
                    </Link>
                  </div>
                  <div className="d-grid">
                    <button
                      className="btn btn-primary btn-login text-uppercase fw-bold"
                      type="submit"
                      onClick={(e) => {
                        e.preventDefault();
                        sendRegisterData();
                      }}
                    >
                      Register
                    </button>
                  </div>
                  <hr className="my-4" />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Register;

export const getServerSideProps = async ({
  req,
  res,
}: {
  req: NextApiRequest;
  res: NextApiResponse;
}) => {
  const [userIsLoggued] = await validateSession(req, res);
  if (userIsLoggued) {
    return {
      redirect: {
        destination: "/hits",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};
